# Generated by Django 5.2 on 2025-04-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=100, unique=True)),
                ('student_phone', models.CharField(max_length=15, unique=True)),
                ('student_address', models.TextField()),
                ('student_dob', models.DateField()),
                ('student_image', models.ImageField(upload_to='images/')),
                ('student_course', models.CharField(max_length=100)),
                ('student_enrollment_date', models.DateField()),
                ('student_document', models.FileField(upload_to='documents/')),
                ('student_status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['student_name'],
            },
        ),
    ]
